MODEL:
  PRETRAIN_PATH: 'vit_base_ics_cfs_lup.pth'
  PRETRAIN_HW_RATIO: 2
  METRIC_LOSS_TYPE: 'prr_triplet'   
  IF_LABELSMOOTH: 'off'
  IF_WITH_CENTER: 'no'
  NAME: 'transformer'
  NO_MARGIN: True
  DEVICE_ID: ('4')
  TRANSFORMER_TYPE: 'vit_base_patch16_224_TransReID'
  STRIDE_SIZE: [16, 16]
  STEM_CONV: True
  TRIPLET_LOSS_WEIGHT: 1.0
  INTERACTION_INTERVAL: 1   #Frequency


INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  PROB: 0.5 # random horizontal flip
  RE_PROB: 0.5 # random erasing
  PADDING: 10
  PIXEL_MEAN: [0.1315, 0.1268, 0.1209]
  PIXEL_STD: [0.0954, 0.0954, 0.0888]

DATASETS:
  NAMES: ('night600')
  ROOT_DIR: ('/your dataset root dir')

DATALOADER:
  SAMPLER: 'softmax_triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 8

SOLVER:
  HARD_EXAMPLE_POS_K: 3   #s_pos
  HARD_EXAMPLE_NEG_K: 7   #s_neg

  OPTIMIZER_NAME: 'SGD'
  MAX_EPOCHS: 120
  BASE_LR: 0.0004
  WARMUP_EPOCHS: 20
  IMS_PER_BATCH: 64
  WARMUP_METHOD: 'cosine'
  LARGE_FC_LR: False
  CHECKPOINT_PERIOD: 120   
  LOG_PERIOD: 50
  EVAL_PERIOD: 10
  WEIGHT_DECAY:  1e-4
  WEIGHT_DECAY_BIAS: 1e-4
  BIAS_LR_FACTOR: 2

TEST:
  EVAL: True
  IMS_PER_BATCH: 64
  RE_RANKING: False
  NECK_FEAT: 'before'
  FEAT_NORM: 'yes'
  TEST_EPOCHS: best_mAP

OUTPUT_DIR: './night600'
